config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  devise_for :users, :controllers => {
   :registrations => 'users/registrations',
  }

  root to: 'users#top'
  #users controller
  get '/users/:id/unsubscribe', to: 'users#unsubscribe', as: "users_unsubscribe"
  get '/users/unsubscribe/complete', to: 'users#complete'
  get '/users/:id/favorite', to: 'users#favorite', as: "user_favorite_page"
  patch '/users/:id/status_user', to: 'users#status_user', as: "user_status"
  get '/users/travelers', to: 'users#index_traveler'
  get '/users/travelers/search', to: 'users#search_traveler'
  get '/users/locals', to: 'users#index_local'
  get '/users/locals/search', to: 'users#search_local'
  get '/users/locals/sort', to: 'users#sort_local'
  resources :users, only: [:show, :edit, :update, :destroy]
  #posts controller
  get '/posts/top', to: 'posts#top'
  get '/posts/sort', to: 'posts#sort'
  get '/posts/photos', to: 'posts#index_photo', as: "photos"
  resources :posts do
    resources :likes, only:[:create, :destroy]
    resources :comments, only: [:create]
  end
  patch '/posts/:id/status_display', to: 'posts#status_display'
  patch '/posts/:id/status_accomplish', to: 'posts#status_accomplish', as: "status_accomplish"
  patch '/posts/:id/update_accomplish', to: 'posts#update_accomplish', as: "update_accomplish"
  patch '/posts/:id/reset_accomplish', to: 'posts#reset_accomplish', as: "reset_accomplish"
  #comments controller + 一部posts controller下へ
  resources :comments, only: [:edit, :update, :destroy]
  #likes controller  →  posts controller下へ
  #favorites controller
  resources :favorites, only: [:create, :destroy]
  #room controller
  patch '/rooms/status_open'
  resources :rooms, :only => [:create, :show, :index]
  #message controller
  resources :messages, :only => [:create]
  #contact controller
  resources :contacts, only: [:new, :create]
  #notification controller
  resources :notifications, only: [:index]

  #adminsファイル内のcontroller
  namespace :admins do
	  #admins/users controller
    get '/users/travelers', to: 'users#index_traveler'
    get '/users/travelers/search', to: 'users#search_traveler'
    get '/users/travelers/sort', to: 'users#sort_traveler'
    get '/users/locals', to: 'users#index_local'
    get '/users/locals/search', to: 'users#search_local'
    get '/users/locals/sort', to: 'users#sort_local'
    patch '/users/:id/restore', to: 'users#restore', as: "user_restore"
	  resources :users, only: [:show, :edit, :update, :destroy]
    #admins/posts controller
    get '/posts/search', to: 'posts#search'
    get '/posts/sort', to: 'posts#sort'
    patch '/posts/:id/restore', to: 'posts#restore', as: "post_restore"
    resources :posts, only:[:index, :show, :destroy]
    delete '/comments/:id', to: 'posts#comment_destroy', as: "comment_delete"
    #admins/contacts controller
    get '/contacts/search', to: 'contacts#search'
    resources :contacts, only:[:index, :show, :update]
  end
end

app/controllers/admins/users_controller.rb
class Admins::UsersController < ApplicationController

	before_action :authenticate_admin!

	def index_traveler
			@users = User.where(type_user: 0).with_deleted.reverse
	end
	def search_traveler
			if params[:search_flag] == "1"
				if params[:delete_flag] == "0"
					@users = User.where(type_user: 0).with_deleted.where("name_first || name_last LIKE ?", "%#{params[:user_search]}%")
				elsif params[:delete_flag] == "1"
					@users = User.where(type_user: 0).where("name_first || name_last LIKE ?", "%#{params[:user_search]}%")
				elsif params[:delete_flag] == "2"
					@users = User.where(type_user: 0).only_deleted.where("name_first || name_last LIKE ?", "%#{params[:user_search]}%")
				end
			elsif params[:search_flag] == "2"
				if params[:delete_flag] == "0"
					@users = User.where(type_user: 0).with_deleted.where("name_user LIKE ?", "%#{params[:user_name_search]}%")
				elsif params[:delete_flag] == "1"
					@users = User.where(type_user: 0).where("name_user LIKE ?", "%#{params[:user_name_search]}%")
				elsif params[:delete_flag] == "2"
					@users = User.where(type_user: 0).only_deleted.where("name_user LIKE ?", "%#{params[:user_name_search]}%")
				end
			end
			render :index_traveler
	end
	def sort_traveler
			if params[:sort_flag] == "1"
				@most_favorited_usersId = Favorite.most_favorited_userId
				@users = []
				@most_favorited_usersId.each do |f|
					unless User.find_by(id: f).nil? #gem"paranoia"用
						if User.find(f).type_user_before_type_cast == 0
							@users  << User.find(f)
						end
					end
				end
			else params[:sort_flag] == "2"
				@least_favorited_usersId = Favorite.least_favorited_userId
				@users = []
				@least_favorited_usersId.each do |f|
					unless User.find_by(id: f).nil? #gem"paranoia"用
						if User.find(f).type_user_before_type_cast == 0
							@users  << User.find(f)
						end
					end
				end
			end
			render :index_traveler
	end

	def index_local
			@users = User.where(type_user: 1).reverse
	end
	def search_local
			if params[:search_flag] == "1"
				if params[:delete_flag] == "0"
					@users = User.where(type_user: 1).with_deleted.where("name_first || name_last LIKE ?", "%#{params[:user_search]}%")
				elsif params[:delete_flag] == "1"
					@users = User.where(type_user: 1).where("name_first || name_last LIKE ?", "%#{params[:user_search]}%")
				elsif params[:delete_flag] == "2"
					@users = User.where(type_user: 1).only_deleted.where("name_first || name_last LIKE ?", "%#{params[:user_search]}%")
				end
			elsif params[:search_flag] == "2"
				if params[:delete_flag] == "0"
					@users = User.where(type_user: 1).with_deleted.where("name_user LIKE ?", "%#{params[:user_name_search]}%")
				elsif params[:delete_flag] == "1"
					@users = User.where(type_user: 1).where("name_user LIKE ?", "%#{params[:user_name_search]}%")
				elsif params[:delete_flag] == "2"
					@users = User.where(type_user: 1).only_deleted.where("name_user LIKE ?", "%#{params[:user_name_search]}%")
				end
			end
			render :index_local
	end
	def sort_local
			if params[:sort_flag] == "1"
				@most_favorited_usersId = Favorite.most_favorited_userId
				@users = []
				@most_favorited_usersId.each do |f|
					unless User.find_by(id: f).nil? #gem"paranoia"用
						if User.find(f).type_user_before_type_cast == 1
							@users  << User.find(f)
						end
					end
				end
			else params[:sort_flag] == "2"
				@least_favorited_usersId = Favorite.least_favorited_userId
				@users = []
				@least_favorited_usersId.each do |f|
					unless User.find_by(id: f).nil? #gem"paranoia"用
						if User.find(f).type_user_before_type_cast == 1
							@users  << User.find(f)
						end
					end
				end
			end
			render :index_local
	end
	def show
			@user = User.with_deleted.find(params[:id])
			@posts = @user.posts.with_deleted
	end
	def destroy
      user = User.find(params[:id])
      user.destroy
	end
	def restore
      user = User.only_deleted.find(params[:id])
      user.restore
	end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]
  # GET /resource/sign_up
  def new
      @nationality = NATIOALITY
      @country = COUNTRY
      @language = LANGUAGE
      if params[:type_user] == "0"
        @view = 0
      elsif params[:type_user] == "1"
        @view = 1
      end
      super
  end

  # POST /resource
  def create
      @nationality = NATIOALITY
      @country = COUNTRY
      @language = LANGUAGE
      #下記if文はparanoia用
      if User.only_deleted.pluck(:name_user).include?(user_params[:name_user])
        flash[:name_notice] = "This user name is already taken."
        redirect_to new_user_registration_path
      elsif User.only_deleted.pluck(:email).include?(user_params[:email])
        flash[:email_notice] = "This email address is not available."
        redirect_to new_user_registration_path
      else
      #ここまで
        flash[:success] = "You have created account successfully."
        super
      end
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end
  private #paranoia用
    def user_params
        params.require(:user).permit(:type_user, :name_first, :name_last, :name_user, :gender, :birthday, :nationality, :country, :language_first, :language_second, :language_third, :hobby, :introduction, :picture_profile, :picture_background, :email, :deleted_at)
    end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  def after_sign_up_path_for(resource)
    user_path(current_user)
  end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	before_action :authenticate_user!, except: [:top, :complete]

	def index_traveler
      @nationality = NATIOALITY
      @language = LANGUAGE
			@users = User.travelers
	end
	def search_traveler
      @nationality = NATIOALITY
     	@language = LANGUAGE
			if params[:search_flag] == "1"
				@users = User.travelers.where("name_user LIKE ?", "%#{params[:user_search]}%")
			elsif params[:search_flag] == "2"
				@users = User.travelers.where(nationality: params[:nationality])
			elsif  params[:search_flag] == "3"
				@users = User.travelers.where('language_first = ? or language_second = ? or language_third = ?', params[:language], params[:language], params[:language])
			end
			render :index_traveler
	end
	def index_local
      @nationality = NATIOALITY
      @language = LANGUAGE
			@users = User.locals
			@most_favorited_usersId = Favorite.most_favorited_userId_month
			@most_favorited_locals = []
			@most_favorited_usersId.each do |f|
				unless User.find_by(id: f).nil? #gem"paranoia"用
					if User.find(f).type_user_before_type_cast == 1
						@most_favorited_locals  << User.find(f)
						if @most_favorited_locals.count == 5 #ranking5位まで
							break
					    end
					end
				end
			end
	end
	def search_local
      @nationality = NATIOALITY
      @language = LANGUAGE
      @search_flag = 0
			if params[:search_flag] == "1"
				@users = User.locals.where("name_user LIKE ?", "%#{params[:user_search]}%")
			elsif params[:search_flag] == "2"
				@users = User.locals.where(nationality: params[:nationality])
			elsif  params[:search_flag] == "3"
				@users = User.locals.where('language_first = ? or language_second = ? or language_third = ?', params[:language], params[:language], params[:language])
			end
			render :index_local
	end
	def show
			@user = User.find(params[:id])
			@posts_unaccomplish = Post.where(user_id: @user.id, status_accomplishment: 0)
			@posts_accomplish = Post.where(user_id: @user.id, status_accomplishment: 1)
			@favorite_count = @user.followers.count
			# 下記messageのroom
	    @currentroomuser=RoomUser.where(user_id: current_user.id)
    	@roomuser=RoomUser.where(user_id: @user.id)
    	if @user.id != current_user.id
				@currentroomuser.each do |cu|
					@roomuser.each do |u|
					if cu.room_id == u.room_id
						@isRoom = true
						@roomId = cu.room_id
					end
				end
			end
		    if @isRoom
		    else
		        @room = Room.new
		        @roomusernew = RoomUser.new
		    end
	    end
	end
	def favorite
			@user = User.find(params[:id])
			@posts_like = @user.likes.map(&:post)
			@users = @user.followings
			@comments = Comment.where(user_id: @user.id)
			@post_comments = @comments.map{|c| Post.find_by(id: c.post.id)}.uniq
			if @user != current_user
      	redirect_to posts_top_path
      end
	end
	def edit
      @nationality = NATIOALITY
      @country = COUNTRY
			@language = LANGUAGE
      @user = User.find(params[:id])
			if @user != current_user
      	redirect_to posts_top_path
      end
	end
	def update
			@nationality = NATIOALITY
      @country = COUNTRY
			@language = LANGUAGE
	    @user = User.find(params[:id])
	    if @user.update(user_params)
	    	flash[:success] = "You have edited profile successfully."
	    	redirect_to user_path(@user)
	    else
	    	flash[:error] = "error!!"
	    	render :edit
	    end
	end
	def status_user
			@user = User.find(params[:id])
			if @user.status_user_before_type_cast == 0
				@user.update(status_user: 1)
    	elsif @user.status_user_before_type_cast == 1
				@user.update(status_user: 2)
    	elsif @user.status_user_before_type_cast == 2
   			@user.update(status_user: 0)
   		end
	end
	def destroy
			current_user.destroy
			Devise.sign_out_all_scopes ? sign_out : sign_out(current_user)
			redirect_to users_unsubscribe_complete_path
	end
	def unsubscribe
      @user = User.find(params[:id])
			if @user != current_user
      	redirect_to posts_top_path
    	end
	end

	private
		def user_params
				params.require(:user).permit(:type_user, :name_first, :name_last, :name_user, :gender, :birthday, :nationality, :country, :language_first, :language_second, :language_third, :hobby, :introduction, :picture_profile, :picture_background)
		end
end

app/helpers/admins/users_helper.rb
module Admins::UsersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/complete.html.erb
<div class="container-fluid">
	<div class="row">
		<div class="col-md-12">
  		<h1 class="title_type1">Unsubscribe Request Complete</h1>
  		<h3>We're sad to see you leave. You have successfuly unsubcribe.</h3>
		</div>
	</div>
</div>

app/views/users/show.html.erb
<div class="user-background">
	<% if @user.picture_background? %>
		<%= image_tag asset_path @user.picture_background.background.url %>
	<% else %>
		<%= image_tag asset_path "default.jpg" %>
	<% end %>
</div>
<div class="profile-headline">
	<% if @user.type_user_before_type_cast == 0 %>
		<h1 class="title_type1_traveler"><%= @user.type_user %></h1>
	<% elsif @user.type_user_before_type_cast == 1 %>
		<h1 class="title_type1_local"><%= @user.type_user %></h1>
	<% end %>
</div>
<div class="user-headline clearfix">
  <div class="user-headline-left">
    <% if @user == current_user %>
			<%= link_to "your favorites", user_favorite_page_path(current_user), class:"label label-default", :style=>"background-color: #c77eb5;" %>
			<%= link_to "edit profile", edit_user_path(current_user), class:"label label-default", :style=>"background-color: #c77eb5;" %>
			<%= link_to "unsubscribe", users_unsubscribe_path(current_user), class:"label label-default", :style=>"background-color: #c77eb5;" %>
		<% end %>
	<!-- message機能 -->
		<% if @user != current_user %>
		<% if @user.status_user_before_type_cast != 2 %>
			<% if @isRoom == true %>
	    	<%= link_to "message", room_path(@roomId), class:"label label-default", :style=>"background-color: #c77eb5;" %>
	  	<% else %>
		    <%= form_for @room do |f| %>
		      <%= fields_for @roomusernew do |e| %>
		        <%= e.hidden_field :user_id, value:@user.id %>
		    	<% end %>
	      	<%= f.submit "new message", :style=>"background-color: #c77eb5; color: white; width: 100px; border-radius: 5px;" %>
	    	<% end %>
	  	<% end %>
	  <% end %>
		<% end %>
	<!-- ここまで -->
	</div>
	<div class="user-headline-image">
		<% if @user.picture_profile? %>
			<%= image_tag asset_path @user.picture_profile.profile.url %>
		<% else %>
			<%= image_tag asset_path "default.jpg" %>
		<% end %>
	</div>
	<div class="user-headline-rigth">
		<p>User Name</p>
		<p style="font-size: 30px; font-weight: bold;"><%= @user.name_user %></p>
	<!-- ユーザに対するいいね機能 -->
		<% if current_user != @user %>
		  <% if current_user.following?(@user) %>
			  <%= link_to favorite_path(follow_id: @user.id), id:"favorited", remote: true, method: :delete do %>
					<%= icon 'fa', 'heart', :style=>"color: red; font-size: 30px;"%>
			  <% end %>
			  <%= link_to favorites_path(follow_id: @user.id), id:"notfavorited", :style=>"display: none;", remote: true, method: :post do %>
					<%= icon 'fa', 'heart', :style=>"color: grey; font-size: 30px;"%>
			  <% end %>
		  <% else %>
			  <%= link_to favorite_path(follow_id: @user.id), id:"favorited", :style=>"display: none;", remote: true, method: :delete do %>
					<%= icon 'fa', 'heart', :style=>"color: red; font-size: 30px;"%>
			  <% end %>
			  <%= link_to favorites_path(follow_id: @user.id), id:"notfavorited", remote: true, method: :post do %>
					<%= icon 'fa', 'heart', :style=>"color: grey; font-size: 30px;"%>
			  <% end %>
		  <% end %>
		  <span id="favorite_count" style="font-size: 20px;"><%= @favorite_count %> favorites</span>
		<% else %>
		  <span id="favorite_count" style="font-size: 20px;"><%= @favorite_count %> favorites</span>
		<% end %>
	<!-- ここまで -->
		<% if @user == current_user %>
			<% if @user.status_user_before_type_cast == 0 %>
				<%= link_to @user.status_user, user_status_path(@user), method: :patch, remote: true, :style=>"font-size: 20px;", class:"label label-success" %>
			<% elsif @user.status_user_before_type_cast == 1 %>
				<%= link_to @user.status_user, user_status_path(@user), method: :patch, remote: true, :style=>"font-size: 20px;", class:"label label-warning" %>
			<% elsif @user.status_user_before_type_cast == 2 %>
				<%= link_to @user.status_user, user_status_path(@user), method: :patch, remote: true, :style=>"font-size: 20px;", class:"label label-danger" %>
			<% end %>
		<% else %>
			<% if @user.status_user_before_type_cast == 0 %>
				<span class="label label-success" style="font-size: 20px;"><%= @user.status_user %></span>
			<% elsif @user.status_user_before_type_cast == 1 %>
				<span class="label label-warning" style="font-size: 20px;"><%= @user.status_user %></span>
			<% elsif @user.status_user_before_type_cast == 2 %>
				<span class="label label-danger" style="font-size: 20px;"><%= @user.status_user %></span>
			<% end %>
		<% end %>
		<% if @user.type_user_before_type_cast == 0 %>
			<p style="font-size: 20px;"><%= @posts_unaccomplish.count %> Trickets / <%= @posts_accomplish.count %> accomplishments</p>
		<% end %>
	</div>
</div>

<% if flash[:success] %>
	<div id="flash" class="alert alert-success" role="alert">
		<%= flash[:success] %>
	</div>
<% end %>

<div class="container-fluid">
	<div class="user-content">
		<div class="row">
			<div class="col-md-12">
				<div class="user-profile-headline">
					<% if @user.type_user_before_type_cast == 0 %>
						<h1 class="title_type1_traveler">Profile</h1>
					<% elsif @user.type_user_before_type_cast == 1 %>
						<h1 class="title_type1_local">Profile</h1>
					<% end %>
				</div>
			</div>
		</div>
		<div class="row">
			<div class="user-profile-content">
				<div class="col-md-6">
					<table class="table table-condensed">
						<tbody>
							<tr>
								<th>username</th>
								<td><%= @user.name_user %></td>
							</tr>
							<tr>
								<th>gender</th>
								<td><%= @user.gender %></td>
							</tr>
							<tr>
								<th>age</th>
								<td><%= (Date.today.strftime("%Y%m%d").to_i - @user.birthday.strftime("%Y%m%d").to_i) / 10000 %></td>
							</tr>
							<tr>
								<th>nationality</th>
								<td><%= @user.nationality %></td>
							</tr>
							<tr>
								<th>first language</th>
								<td><%= @user.language_first %></td>
							</tr>
							<% if @user.language_second.present? %>
							<tr>
								<th>second language</th>
								<td><%= @user.language_second %></td>
							</tr>
							<% end %>
							<% if @user.language_third.present? %>
							<tr>
								<th>third language</th>
								<td><%= @user.language_third %></td>
							</tr>
							<% end %>
						</tbody>
					</table>
				</div>
				<div class="col-md-6">
					<table class="table table-condensed">
						<tbody>
							<tr>
								<th>hobby</th>
								<td><%= @user.hobby %></td>
							</tr>
							<tr>
								<th>introduction</th>
								<td><%= @user.introduction %></td>
							</tr>
						</tbody>
					</table>
				</div>
			</div>
		</div>
		<% if @user.type_user_before_type_cast == 0 %>
			<div class="row">
				<div class="col-md-12">
					<div class="user-Tricket-headline clearfix">
						<h1 class="title_type1_traveler" style="margin: 0; float: left">Trickets</h1>
						<% if @user == current_user %>
							<h3 style="margin: 12px 0 20px 0; float: left;"><%= link_to "new Tricket", new_post_path, class:"label label-default", :style=>"background-color: #c77eb5;" %></h3>
						<% end %>
					</div>
					<% if @posts_unaccomplish.exists? %>
						<% if @posts_unaccomplish.where(status_display: 0).exists? || @user == current_user %>
							<% @posts_unaccomplish.reverse.each do |p| %>
								<% unless p.status_display == 1 && @user != current_user %>
									<div class="user-Tricket-content">
										<div class="panel panel-default">
											<div class="panel-heading" style="background-color:#f8b500;">
												<h5 class="panel-title">Title: <%= p.title.truncate(50) %></h5>
											</div>
											<div class="panel-body">
												<h4 class="label label-default"><%= p.area %></h4>
												<h4 class="label label-default"><%= p.season %></h4>
												<h4 class="label label-default"><%= p.interest %></h4>
												<div style="float:right;">
													<%= link_to "Tricket detail", post_path(p.id), class:"label label-default", :style=>"background-color: #c77eb5" %>
													<% if @user == current_user %>
														<%= link_to "edit Tricket", edit_post_path(p.id), class:"label label-default", :style=>"background-color: #c77eb5" %>
													<% end %>
												</div>
											</div>
										</div>
									</div>
								<% end %>
							<% end %>
						<% else %>
							<p>There is no Tricket.</p>
						<% end %>
					<% else %>
						<p>There is no Tricket.</p>
					<% end %>
				</div>
			</div>
			<div class="row">
				<div class="col-md-12">
					<div class="user-accomplish-headline">
						<h1 class="title_type1_traveler" style="margin: 0; border-color:#5cb85c;">Accomplishments</h1>
					</div>
					<% if @posts_accomplish.exists? %>
						<% if @posts_accomplish.where(status_display: 0).exists? || @user == current_user %>
							<% @posts_accomplish.reverse.each do |p| %>
								<% unless p.status_display == 1 && @user != current_user %>
									<div class="user-Tricket-content">
										<div class="panel panel-default">
											<div class="panel-heading" style="background-color:#5cb85c">
												<h5 class="panel-title">Title: <%= p.title %></h5>
											</div>
											<div class="panel-body">
												<h4 class="label label-default"><%= p.area %></h4>
												<h4 class="label label-default"><%= p.season %></h4>
												<h4 class="label label-default"><%= p.interest %></h4>
												<h4 class="label label-success"><%= p.status_accomplishment %></h4>
												<div style="float:right;">
													<%= link_to "Tricket detail", post_path(p.id), class:"label label-default", :style=>"background-color: #c77eb5" %>
													<% if @user == current_user %>
														<%= link_to "edit Tricket", edit_post_path(p.id), class:"label label-default", :style=>"background-color: #c77eb5" %>
													<% end %>
												</div>
											</div>
										</div>
									</div>
								<% end %>
							<% end %>
						<% else %>
							<p>There is no accomplishment.</p>
						<% end %>
					<% else %>
						<p>There is no accomplishment.</p>
					<% end %>
				</div>
			</div>
		<% end %>
	</div>
</div>