config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  devise_for :users, :controllers => {
   :registrations => 'users/registrations',
  }

  root to: 'users#top'
  #users controller
  get '/users/:id/unsubscribe', to: 'users#unsubscribe', as: "users_unsubscribe"
  get '/users/unsubscribe/complete', to: 'users#complete'
  get '/users/:id/favorite', to: 'users#favorite', as: "user_favorite_page"
  patch '/users/:id/status_user', to: 'users#status_user', as: "user_status"
  get '/users/travelers', to: 'users#index_traveler'
  get '/users/travelers/search', to: 'users#search_traveler'
  get '/users/locals', to: 'users#index_local'
  get '/users/locals/search', to: 'users#search_local'
  get '/users/locals/sort', to: 'users#sort_local'
  resources :users, only: [:show, :edit, :update, :destroy]
  #posts controller
  get '/posts/top', to: 'posts#top'
  get '/posts/sort', to: 'posts#sort'
  get '/posts/photos', to: 'posts#index_photo', as: "photos"
  resources :posts do
    resources :likes, only:[:create, :destroy]
    resources :comments, only: [:create]
  end
  patch '/posts/:id/status_display', to: 'posts#status_display'
  patch '/posts/:id/status_accomplish', to: 'posts#status_accomplish', as: "status_accomplish"
  patch '/posts/:id/update_accomplish', to: 'posts#update_accomplish', as: "update_accomplish"
  patch '/posts/:id/reset_accomplish', to: 'posts#reset_accomplish', as: "reset_accomplish"
  #comments controller + 一部posts controller下へ
  resources :comments, only: [:edit, :update, :destroy]
  #likes controller  →  posts controller下へ
  #favorites controller
  resources :favorites, only: [:create, :destroy]
  #room controller
  patch '/rooms/status_open'
  resources :rooms, :only => [:create, :show, :index]
  #message controller
  resources :messages, :only => [:create]
  #contact controller
  resources :contacts, only: [:new, :create]
  #notification controller
  resources :notifications, only: [:index]

  #adminsファイル内のcontroller
  namespace :admins do
	  #admins/users controller
    get '/users/travelers', to: 'users#index_traveler'
    get '/users/travelers/search', to: 'users#search_traveler'
    get '/users/travelers/sort', to: 'users#sort_traveler'
    get '/users/locals', to: 'users#index_local'
    get '/users/locals/search', to: 'users#search_local'
    get '/users/locals/sort', to: 'users#sort_local'
    patch '/users/:id/restore', to: 'users#restore', as: "user_restore"
	  resources :users, only: [:show, :edit, :update, :destroy]
    #admins/posts controller
    get '/posts/search', to: 'posts#search'
    get '/posts/sort', to: 'posts#sort'
    patch '/posts/:id/restore', to: 'posts#restore', as: "post_restore"
    resources :posts, only:[:index, :show, :destroy]
    delete '/comments/:id', to: 'posts#comment_destroy', as: "comment_delete"
    #admins/contacts controller
    get '/contacts/search', to: 'contacts#search'
    resources :contacts, only:[:index, :show, :update]
  end
end

app/controllers/admins/users_controller.rb
class Admins::UsersController < ApplicationController

	before_action :authenticate_admin!

	def index_traveler
			@users = User.where(type_user: 0).with_deleted.reverse
	end
	def search_traveler
			if params[:search_flag] == "1"
				if params[:delete_flag] == "0"
					@users = User.where(type_user: 0).with_deleted.where("name_first || name_last LIKE ?", "%#{params[:user_search]}%")
				elsif params[:delete_flag] == "1"
					@users = User.where(type_user: 0).where("name_first || name_last LIKE ?", "%#{params[:user_search]}%")
				elsif params[:delete_flag] == "2"
					@users = User.where(type_user: 0).only_deleted.where("name_first || name_last LIKE ?", "%#{params[:user_search]}%")
				end
			elsif params[:search_flag] == "2"
				if params[:delete_flag] == "0"
					@users = User.where(type_user: 0).with_deleted.where("name_user LIKE ?", "%#{params[:user_name_search]}%")
				elsif params[:delete_flag] == "1"
					@users = User.where(type_user: 0).where("name_user LIKE ?", "%#{params[:user_name_search]}%")
				elsif params[:delete_flag] == "2"
					@users = User.where(type_user: 0).only_deleted.where("name_user LIKE ?", "%#{params[:user_name_search]}%")
				end
			end
			render :index_traveler
	end
	def sort_traveler
			if params[:sort_flag] == "1"
				@most_favorited_usersId = Favorite.most_favorited_userId
				@users = []
				@most_favorited_usersId.each do |f|
					unless User.find_by(id: f).nil? #gem"paranoia"用
						if User.find(f).type_user_before_type_cast == 0
							@users  << User.find(f)
						end
					end
				end
			else params[:sort_flag] == "2"
				@least_favorited_usersId = Favorite.least_favorited_userId
				@users = []
				@least_favorited_usersId.each do |f|
					unless User.find_by(id: f).nil? #gem"paranoia"用
						if User.find(f).type_user_before_type_cast == 0
							@users  << User.find(f)
						end
					end
				end
			end
			render :index_traveler
	end

	def index_local
			@users = User.where(type_user: 1).reverse
	end
	def search_local
			if params[:search_flag] == "1"
				if params[:delete_flag] == "0"
					@users = User.where(type_user: 1).with_deleted.where("name_first || name_last LIKE ?", "%#{params[:user_search]}%")
				elsif params[:delete_flag] == "1"
					@users = User.where(type_user: 1).where("name_first || name_last LIKE ?", "%#{params[:user_search]}%")
				elsif params[:delete_flag] == "2"
					@users = User.where(type_user: 1).only_deleted.where("name_first || name_last LIKE ?", "%#{params[:user_search]}%")
				end
			elsif params[:search_flag] == "2"
				if params[:delete_flag] == "0"
					@users = User.where(type_user: 1).with_deleted.where("name_user LIKE ?", "%#{params[:user_name_search]}%")
				elsif params[:delete_flag] == "1"
					@users = User.where(type_user: 1).where("name_user LIKE ?", "%#{params[:user_name_search]}%")
				elsif params[:delete_flag] == "2"
					@users = User.where(type_user: 1).only_deleted.where("name_user LIKE ?", "%#{params[:user_name_search]}%")
				end
			end
			render :index_local
	end
	def sort_local
			if params[:sort_flag] == "1"
				@most_favorited_usersId = Favorite.most_favorited_userId
				@users = []
				@most_favorited_usersId.each do |f|
					unless User.find_by(id: f).nil? #gem"paranoia"用
						if User.find(f).type_user_before_type_cast == 1
							@users  << User.find(f)
						end
					end
				end
			else params[:sort_flag] == "2"
				@least_favorited_usersId = Favorite.least_favorited_userId
				@users = []
				@least_favorited_usersId.each do |f|
					unless User.find_by(id: f).nil? #gem"paranoia"用
						if User.find(f).type_user_before_type_cast == 1
							@users  << User.find(f)
						end
					end
				end
			end
			render :index_local
	end
	def show
			@user = User.with_deleted.find(params[:id])
			@posts = @user.posts.with_deleted
	end
	def destroy
      user = User.find(params[:id])
      user.destroy
	end
	def restore
      user = User.only_deleted.find(params[:id])
      user.restore
	end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]
  # GET /resource/sign_up
  def new
      @nationality = NATIOALITY
      @country = COUNTRY
      @language = LANGUAGE
      if params[:type_user] == "0"
        @view = 0
      elsif params[:type_user] == "1"
        @view = 1
      end
      super
  end

  # POST /resource
  def create
      @nationality = NATIOALITY
      @country = COUNTRY
      @language = LANGUAGE
      #下記if文はparanoia用
      if User.only_deleted.pluck(:name_user).include?(user_params[:name_user])
        flash[:name_notice] = "This user name is already taken."
        redirect_to new_user_registration_path
      elsif User.only_deleted.pluck(:email).include?(user_params[:email])
        flash[:email_notice] = "This email address is not available."
        redirect_to new_user_registration_path
      else
      #ここまで
        flash[:success] = "You have created account successfully."
        super
      end
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end
  private #paranoia用
    def user_params
        params.require(:user).permit(:type_user, :name_first, :name_last, :name_user, :gender, :birthday, :nationality, :country, :language_first, :language_second, :language_third, :hobby, :introduction, :picture_profile, :picture_background, :email, :deleted_at)
    end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  def after_sign_up_path_for(resource)
    user_path(current_user)
  end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	before_action :authenticate_user!, except: [:top, :complete]

	def index_traveler
      @nationality = NATIOALITY
      @language = LANGUAGE
			@users = User.travelers
	end
	def search_traveler
      @nationality = NATIOALITY
     	@language = LANGUAGE
			if params[:search_flag] == "1"
				@users = User.travelers.where("name_user LIKE ?", "%#{params[:user_search]}%")
			elsif params[:search_flag] == "2"
				@users = User.travelers.where(nationality: params[:nationality])
			elsif  params[:search_flag] == "3"
				@users = User.travelers.where('language_first = ? or language_second = ? or language_third = ?', params[:language], params[:language], params[:language])
			end
			render :index_traveler
	end
	def index_local
      @nationality = NATIOALITY
      @language = LANGUAGE
			@users = User.locals
			@most_favorited_usersId = Favorite.most_favorited_userId_month
			@most_favorited_locals = []
			@most_favorited_usersId.each do |f|
				unless User.find_by(id: f).nil? #gem"paranoia"用
					if User.find(f).type_user_before_type_cast == 1
						@most_favorited_locals  << User.find(f)
						if @most_favorited_locals.count == 5 #ranking5位まで
							break
					    end
					end
				end
			end
	end
	def search_local
      @nationality = NATIOALITY
      @language = LANGUAGE
      @search_flag = 0
			if params[:search_flag] == "1"
				@users = User.locals.where("name_user LIKE ?", "%#{params[:user_search]}%")
			elsif params[:search_flag] == "2"
				@users = User.locals.where(nationality: params[:nationality])
			elsif  params[:search_flag] == "3"
				@users = User.locals.where('language_first = ? or language_second = ? or language_third = ?', params[:language], params[:language], params[:language])
			end
			render :index_local
	end
	def show
			@user = User.find(params[:id])
			@posts_unaccomplish = Post.where(user_id: @user.id, status_accomplishment: 0)
			@posts_accomplish = Post.where(user_id: @user.id, status_accomplishment: 1)
			@favorite_count = @user.followers.count
			# 下記messageのroom
	    @currentroomuser=RoomUser.where(user_id: current_user.id)
    	@roomuser=RoomUser.where(user_id: @user.id)
    	if @user.id != current_user.id
				@currentroomuser.each do |cu|
					@roomuser.each do |u|
					if cu.room_id == u.room_id
						@isRoom = true
						@roomId = cu.room_id
					end
				end
			end
		    if @isRoom
		    else
		        @room = Room.new
		        @roomusernew = RoomUser.new
		    end
	    end
	end
	def favorite
			@user = User.find(params[:id])
			@posts_like = @user.likes.map(&:post)
			@users = @user.followings
			@comments = Comment.where(user_id: @user.id)
			@post_comments = @comments.map{|c| Post.find_by(id: c.post.id)}.uniq
			if @user != current_user
      	redirect_to posts_top_path
      end
	end
	def edit
      @nationality = NATIOALITY
      @country = COUNTRY
			@language = LANGUAGE
      @user = User.find(params[:id])
			if @user != current_user
      	redirect_to posts_top_path
      end
	end
	def update
			@nationality = NATIOALITY
      @country = COUNTRY
			@language = LANGUAGE
	    @user = User.find(params[:id])
	    if @user.update(user_params)
	    	flash[:success] = "You have edited profile successfully."
	    	redirect_to user_path(@user)
	    else
	    	flash[:error] = "error!!"
	    	render :edit
	    end
	end
	def status_user
			@user = User.find(params[:id])
			if @user.status_user_before_type_cast == 0
				@user.update(status_user: 1)
    	elsif @user.status_user_before_type_cast == 1
				@user.update(status_user: 2)
    	elsif @user.status_user_before_type_cast == 2
   			@user.update(status_user: 0)
   		end
	end
	def destroy
			current_user.destroy
			Devise.sign_out_all_scopes ? sign_out : sign_out(current_user)
			redirect_to users_unsubscribe_complete_path
	end
	def unsubscribe
      @user = User.find(params[:id])
			if @user != current_user
      	redirect_to posts_top_path
    	end
	end

	private
		def user_params
				params.require(:user).permit(:type_user, :name_first, :name_last, :name_user, :gender, :birthday, :nationality, :country, :language_first, :language_second, :language_third, :hobby, :introduction, :picture_profile, :picture_background)
		end
end

app/helpers/admins/users_helper.rb
module Admins::UsersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admins/users/destroy.js.erb
$('#normal_user').hide();
$('.label-success').attr("class", "label label-danger");
$('#deleted_user').show();

app/views/admins/users/index_local.html.erb
<div class="container-fluid">
	<div class="row">
    <div class="col-md-12">
    	<h1 style="text-decoration: underline;">Locals一覧</h1>
    	<div class="admin-Travelers-search">
	    	<div class="search-form-tag">
					<%= form_tag(admins_users_locals_search_path, method: :get) do %>
						<%= label_tag "氏名" %>
						<%= radio_button_tag :delete_flag, 0, checked: true %>全て
						<%= radio_button_tag :delete_flag, 1 %>問題無
						<%= radio_button_tag :delete_flag, 2 %>削除済
						<%= hidden_field_tag :search_flag, 1 %>
						<%= text_field_tag :user_search %>
						<%= submit_tag "検索" %>
					<% end %>
				</div>
	    	<div class="search-form-tag">
					<%= form_tag(admins_users_locals_search_path, method: :get) do %>
						<%= label_tag "ユーザ名" %>
						<%= radio_button_tag :delete_flag, 0, checked: true %>全て
						<%= radio_button_tag :delete_flag, 1 %>問題無
						<%= radio_button_tag :delete_flag, 2 %>削除済
						<%= hidden_field_tag :search_flag, 2 %>
						<%= text_field_tag :user_name_search %>
						<%= submit_tag "検索" %>
					<% end %>
				</div>
    	</div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12">
			<table class="table table-striped">
				<thead>
					<tr>
						<th>id</th>
						<th>氏名</th>
						<th>ユーザ名</th>
						<th>性別</th>
						<th>年齢</th>
						<th>国籍</th>
						<th>人気<%= link_to "▲", admins_users_locals_sort_path(sort_flag: 1) %><%= link_to "▼", admins_users_locals_sort_path(sort_flag: 2) %></th>
						<th>表示</th>
						<th>フラグ</th>
						<th>詳細</th>
					</tr>
				</thead>
				<% @users.each do |user| %>
				<tbody>
					<tr>
						<th style="width: 75px;"><%= user.id %></th>
						<th style="width: 250px;"><%= user.name_first %> <%= user.name_last %></th>
						<td style="width: 200px;"><%= user.name_user.truncate(15) %></td>
						<td style="width: 75px;"><%= user.gender %></td>
						<td style="width: 50px;"><%= (Date.today.strftime("%Y%m%d").to_i - user.birthday.strftime("%Y%m%d").to_i) / 10000 %></td>
						<td style="width: 100px;"><%= user.nationality %></td>
						<td style="width: 75px;"><%= user.followers.count %></td>
						<td style="width: 75px;"><%= user.status_user %></td>
						<% if user.deleted_at.nil? %>
							<td style="width: 75px;">問題無</td>
						<% else %>
							<td style="width: 75px; color: red;">削除済</td>
						<% end %>
						<th style="width: 75px;"><%= link_to "詳細", admins_user_path(user.id) %></td>
					</tr>
				</tbody>
				<% end %>
			</table>
		</div>
	</div>
</div>

app/views/admins/users/restore.js.erb
$('#deleted_user').hide();
$('.label-danger').attr("class", "label label-success");
$('#normal_user').show();

app/views/admins/users/show.html.erb
<div class="container-fluid">
	<div class="row">
		<h1 style="text-decoration: underline; margin-left: 20px;"><%= @user.type_user %>詳細</h1>
		<div class="col-md-6">
			<div class="admin-user-image">
				<% if @user.picture_profile? %>
					<%= image_tag asset_path @user.picture_profile.profile.url %>
				<% else %>
					<%= image_tag asset_path "default.jpg" %>
				<% end %>
			</div>
			<table class="table table-striped">
				<tbody>
					<tr>
						<th>ユーザid</th>
						<th><%= @user.id %></th>
					</tr>
					<tr>
						<th>氏名</th>
						<th><%= @user.name_first %> <%= @user.name_last %></th>
					</tr>
					<tr>
						<th>ユーザ名</th>
						<th><%= @user.name_user %></th>
					</tr>
				</tbody>
			</table>
		</div>
		<div class="col-md-6">
			<table class="table table-striped">
				<tbody>
					<tr>
						<th>性別</th>
						<th><%= @user.gender %></th>
					</tr>
					<tr>
						<th>年齢</th>
						<th><%= (Date.today.strftime("%Y%m%d").to_i - @user.birthday.strftime("%Y%m%d").to_i) / 10000 %></th>
					</tr>
					<tr>
						<th>生年月日</th>
						<th><%= @user.birthday.strftime("%Y/%m/%d") %></th>
					</tr>
					<tr>
						<th>国籍</th>
						<th><%= @user.nationality %></th>
					</tr>
					<tr>
						<th>居住地</th>
						<th><%= @user.country %></th>
					</tr>
					<tr>
						<th>言語1</th>
						<th><%= @user.language_first %></th>
					</tr>
					<tr>
						<th>言語2</th>
						<th><%= @user.language_second %></th>
					</tr>
					<tr>
						<th>言語3</th>
						<th><%= @user.language_third %></th>
					</tr>
					<tr>
						<th>メールアドレス</th>
						<th><%= @user.email %></th>
					</tr>
				</tbody>
			</table>
		</div>
	</div>
	<div class="row">
		<div class="col-md-12">
			<table class="table table-striped">
				<tbody>
					<tr>
						<th>趣味</th>
						<th><%= @user.hobby %></th>
					</tr>
					<tr>
						<th>自己紹介</th>
						<th><%= @user.introduction %></th>
					</tr>
					<tr>
						<th>人気</th>
						<th><%= @user.followers.count %></th>
					</tr>
					<tr>
						<th>利用ステータス</th>
						<th><%= @user.status_user %></th>
					</tr>
					<tr>
						<th>削除フラグ</th>
						<% if @user.deleted_at.nil? %>
						<th><%= link_to "問題無 (削除しますか?)", admins_user_path(@user), method: :delete, remote: true, :style=>"font-size: 20px;", id:"normal_user", class:"label label-success", data: { confirm: "このユーザを削除しますか?" } %>
							<%= link_to "消去済 (復活しますか?)", admins_user_restore_path(@user), method: :patch, remote: true, :style=>"font-size: 20px; display: none;", id:"deleted_user", class:"label label-danger", data: { confirm: "このユーザを復活しますか?" } %></th>
						<% else %>
						<th><%= link_to "問題無 (削除しますか?)", admins_user_path(@user), method: :delete, remote: true, :style=>"font-size: 20px; display: none;", id:"normal_user", class:"label label-success", data: { confirm: "このユーザを削除しますか?" } %>
							<%= link_to "消去済 (復活しますか?)", admins_user_restore_path(@user), method: :patch, remote: true, :style=>"font-size: 20px;", id:"deleted_user", class:"label label-danger", data: { confirm: "このユーザを復活しますか?" } %></th>
						<% end %>
					</tr>
				</tbody>
			</table>
		</div>
	</div>
	<div class="row">
		<h3 style="text-decoration: underline; margin-left: 20px;">ユーザのコメント一覧</h3>
		<div class="col-md-12">
			<table class="table table-condensed">
				<% @user.comments.reverse.each do |comment| %>
				<tbody class="comments-content">
					<tr>
						<th style="width: 250px;"><%= link_to "#{comment.post.title.truncate(30)}", admins_post_path(comment.post.id) %></th>
						<td style="width: 550px;"><%= comment.content %></td>
						<td><%= comment.created_at.to_s(:long) %></td>
						<td><%= link_to "delete", admins_comment_delete_path(comment.id), method: :delete, data: { confirm: "Are you sure to delete this comment?" } %></td>
					</tr>
				</tbody>
				<% end %>
			</table>
		</div>
	</div>
	<% if @user.type_user_before_type_cast == 0 %>
	<div class="row">
		<h3 style="text-decoration: underline; margin-left: 20px;">ユーザのTricket一覧</h3>
		<div class="col-md-12">
			<table class="table table-striped">
				<thead>
					<tr>
						<th>id</th>
						<th>投稿日</th>
						<th>タイトル</th>
						<th>人気</th>
						<th>達成</th>
						<th>表示</th>
						<th>フラグ</th>
					</tr>
				</thead>
				<% @posts.each do |post| %>
				<tbody>
					<tr>
						<th style="width: 75px;"><%= post.id %></th>
						<td style="width: 200px;"><%= post.created_at.strftime("%Y年%-m月%-d日 %-H時%-M分") %></td>
						<td style="width: 350px;"><%= post.title.truncate(40) %></td>
						<td style="width: 100px;"><%= post.likes.count %></td>
						<td style="width: 75px;"><%= post.status_accomplishment_i18n %></td>
						<td style="width: 75px;"><%= post.status_display_i18n %></td>
						<% if post.deleted_at.nil? %>
							<td style="width: 75px;">問題無</td>
						<% else %>
							<td style="width: 75px; color: red;">削除済</td>
						<% end %>
					</tr>
				</tbody>
				<% end %>
			</table>
		</div>
	</div>
	<% end %>
</div>