config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  devise_for :users, :controllers => {
   :registrations => 'users/registrations',
  }

  root to: 'users#top'
  #users controller
  get '/users/:id/unsubscribe', to: 'users#unsubscribe', as: "users_unsubscribe"
  get '/users/unsubscribe/complete', to: 'users#complete'
  get '/users/:id/favorite', to: 'users#favorite', as: "user_favorite_page"
  patch '/users/:id/status_user', to: 'users#status_user', as: "user_status"
  get '/users/travelers', to: 'users#index_traveler'
  get '/users/travelers/search', to: 'users#search_traveler'
  get '/users/locals', to: 'users#index_local'
  get '/users/locals/search', to: 'users#search_local'
  get '/users/locals/sort', to: 'users#sort_local'
  resources :users, only: [:show, :edit, :update, :destroy]
  #posts controller
  get '/posts/top', to: 'posts#top'
  get '/posts/sort', to: 'posts#sort'
  get '/posts/photos', to: 'posts#index_photo', as: "photos"
  resources :posts do
    resources :likes, only:[:create, :destroy]
    resources :comments, only: [:create]
  end
  patch '/posts/:id/status_display', to: 'posts#status_display'
  patch '/posts/:id/status_accomplish', to: 'posts#status_accomplish', as: "status_accomplish"
  patch '/posts/:id/update_accomplish', to: 'posts#update_accomplish', as: "update_accomplish"
  patch '/posts/:id/reset_accomplish', to: 'posts#reset_accomplish', as: "reset_accomplish"
  #comments controller + 一部posts controller下へ
  resources :comments, only: [:edit, :update, :destroy]
  #likes controller  →  posts controller下へ
  #favorites controller
  resources :favorites, only: [:create, :destroy]
  #room controller
  patch '/rooms/status_open'
  resources :rooms, :only => [:create, :show, :index]
  #message controller
  resources :messages, :only => [:create]
  #contact controller
  resources :contacts, only: [:new, :create]
  #notification controller
  resources :notifications, only: [:index]

  #adminsファイル内のcontroller
  namespace :admins do
	  #admins/users controller
    get '/users/travelers', to: 'users#index_traveler'
    get '/users/travelers/search', to: 'users#search_traveler'
    get '/users/travelers/sort', to: 'users#sort_traveler'
    get '/users/locals', to: 'users#index_local'
    get '/users/locals/search', to: 'users#search_local'
    get '/users/locals/sort', to: 'users#sort_local'
    patch '/users/:id/restore', to: 'users#restore', as: "user_restore"
	  resources :users, only: [:show, :edit, :update, :destroy]
    #admins/posts controller
    get '/posts/search', to: 'posts#search'
    get '/posts/sort', to: 'posts#sort'
    patch '/posts/:id/restore', to: 'posts#restore', as: "post_restore"
    resources :posts, only:[:index, :show, :destroy]
    delete '/comments/:id', to: 'posts#comment_destroy', as: "comment_delete"
    #admins/contacts controller
    get '/contacts/search', to: 'contacts#search'
    resources :contacts, only:[:index, :show, :update]
  end
end

app/models/contact.rb
class Contact < ApplicationRecord

  validates :subject, presence: true, length: {in: 1..50}
  validates :content, presence: true, length: {in: 30..500}

	belongs_to :user

	enum status_reply: { notyet: 0, replyed: 1 }
end

app/controllers/admins/contacts_controller.rb
class Admins::ContactsController < ApplicationController

	before_action :authenticate_admin!

	def index
		  @contacts = Contact.all.reverse
	end
	def search
  		if params[:search_flag] == "1"
  			@contacts = Contact.where("created_at LIKE ?", "%#{params[:date_search]}%")
  		elsif params[:search_flag] == "2"
  			@contacts = Contact.joins(:user).where("name_user LIKE ?", "%#{params[:user_search]}%")
  		elsif params[:search_flag] == "3"
  			@contacts = Contact.joins(:user).where("email LIKE ?", "%#{params[:email_search]}%")
  		elsif params[:search_flag] == "4" && params[:sort_flag] == "0"
  			@contacts = Contact.where(status_reply: 0).order('created_at DESC')
  		elsif params[:search_flag] == "4" && params[:sort_flag] == "1"
  			@contacts = Contact.where(status_reply: 1)
  		end
  		render :index
	end
	def show
  		@contact = Contact.find(params[:id])
  		@user = @contact.user
	end
	def update
      @contact = Contact.find(params[:id])
		  @user = @contact.user
    	if  @contact.update(contact_params)
    		if @contact.reply_language == 1
    			ContactMailer.send_when_admin_reply_japanese(@user, @contact).deliver
        	flash[:success] = "日本語で送信が完了いたしました。"
        else @contact.reply_language == 2
				  ContactMailer.send_when_admin_reply_english(@user, @contact).deliver
		      flash[:success] = "英語で送信が完了いたしました。"
		    end
        @contact.update(status_reply: 1)
    		render :show
      else
        flash[:error] = "エラー。送信でできませんでした。"
    		render :show
      end
	end

	private
    def contact_params
    	params.require(:contact).permit(:user_id, :subject, :content, :reply, :status_reply, :reply_language)
    end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController

	before_action :authenticate_user!

	def new
		  @contact = Contact.new
	end
	def create
		  @contact = Contact.new(contact_params)
    	@contact.user_id = current_user.id
    	if @contact.save
        ContactMailer.send_when_user_message(current_user, @contact).deliver
        @contact = Contact.new
        flash[:success] = "You have sent the message successfully."
    		render :new
      else
        flash[:error] = "error!!"
        render :new
      end
	end

	private
    def contact_params
      params.require(:contact).permit(:user_id, :subject, :content, :reply)
    end
end

app/helpers/admins/contacts_helper.rb
module Admins::ContactsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/views/admins/contacts/index.html.erb
<div class="container-fluid">
	<div class="row">
    <div class="col-md-12">
    	<h1 style="text-decoration: underline;">お問い合わせ一覧</h1>
    	<div class="admin-contacts-search">
    		<div class="search-form-tag">
    			<%= form_tag(admins_contacts_search_path, method: :get) do %>
						<%= label_tag "日付(yy-mm-dd)" %>
						<%= hidden_field_tag :search_flag, 1 %>
						<%= text_field_tag :date_search %>
						<%= submit_tag "検索" %>
					<% end %>
				</div>
    		<div class="search-form-tag">
					<%= form_tag(admins_contacts_search_path, method: :get) do %>
						<%= label_tag "ユーザ名" %>
						<%= hidden_field_tag :search_flag, 2 %>
						<%= text_field_tag :user_search %>
						<%= submit_tag "検索" %>
					<% end %>
				</div>
    		<div class="search-form-tag">
					<%= form_tag(admins_contacts_search_path, method: :get) do %>
						<%= label_tag "eメールアドレス" %>
						<%= hidden_field_tag :search_flag, 3 %>
						<%= text_field_tag :email_search %>
						<%= submit_tag "検索" %>
					<% end %>
				</div>
    		<div class="search-form-tag">
    			<%= label_tag "返信有無ソート：" %>
	  			<%= link_to "返信未", admins_contacts_search_path(search_flag: 4, sort_flag: 0), :style=>"width: 75px; font-size: 16px; background-color: red; color:white;" %>
	  			<%= link_to "返信済", admins_contacts_search_path(search_flag: 4, sort_flag: 1), :style=>"width: 75px; font-size: 16px; background-color: green; color:white;" %>
				</div>
    	</div>
    </div>
	</div>
  <div class="row">
    <div class="col-md-12">
			<table class="table table-striped">
				<thead>
					<tr>
						<th>id</th>
						<th>日付</th>
						<th>ユーザid</th>
						<th>ユーザ名</th>
						<th>eメールアドレス</th>
						<th>件名</th>
						<th>返信有無</th>
						<th>詳細</th>
					</tr>
				</thead>
				<% @contacts.each do |contact| %>
				<tbody>
					<tr>
						<th style="width: 75px;"><%= contact.id %></th>
						<td style="width: 200px;"><%= contact.created_at.strftime("%Y年%-m月%-d日 %-H時%-M分") %></td>
						<td style="width: 75px;"><%= contact.user.id %></td>
						<td style="width: 200px;"><%= contact.user.name_user.truncate(15) %></td>
						<td style="width: 200px;"><%= contact.user.email %></td>
						<td><%= contact.subject.truncate(30) %></td>
						<% if contact.status_reply_before_type_cast == 0 %>
							<th style="width: 75px; background-color: red; color: white; text-align: center;"><%= contact.status_reply_i18n %></td>
						<% elsif contact.status_reply_before_type_cast == 1 %>
							<th style="width: 75px; background-color: green; color: white; text-align: center;"><%= contact.status_reply_i18n %></td>
						<% end %>
						<th style="width: 75px;"><%= link_to "詳細" ,admins_contact_path(contact.id) %></td>
					</tr>
				</tbody>
				<% end %>
			</table>
		</div>
	</div>
</div>

app/views/admins/contacts/show.html.erb
<div class="container-fluid">
	<div class="row">
    <div class="col-md-12">
    	<h1 style="text-decoration: underline;">お問い合わせ詳細</h1>
			<% if @contact.status_reply_before_type_cast == 0 %>
				<div style="width: 75px; background-color: red; color: white; text-align: center;"><%= @contact.status_reply_i18n %></div>
			<% elsif @contact.status_reply_before_type_cast == 1 %>
				<div style="width: 75px; background-color: green; color: white; text-align: center;"><%= @contact.status_reply_i18n %></div>
			<% end %>
			<table class="table table-bordered">
				<tr>
					<td style="width:150px;">お問い合わせid</td>
					<td><%= @contact.id %></td>
				</tr>
				<tr>
					<td>日付</td>
					<td><%= @contact.created_at.strftime("%Y年%-m月%-d日 %-H時%-M分") %></td>
				</tr>
				<tr>
					<td>ユーザid</td>
					<td><%= @contact.user.id %></td>
				</tr>
				<tr>
					<td>ユーザ名</td>
					<td><%= @contact.user.name_user %></td>
				</tr>
				<tr>
					<td>eメールアドレス</td>
					<td><%= @contact.user.email %></td>
				</tr>
				<tr>
					<td>件名</td>
					<td><%= @contact.subject %></td>
				</tr>
				<tr>
					<td>本文</td>
					<td><%= @contact.content %></td>
				</tr>
			</table>
			<%= button_to "一覧へ戻る" ,admins_contacts_path, method: :get %>
		</div>
	</div>
	<div class="row">
    <div class="col-md-6">
			<h1 style="text-decoration: underline;">お問い合わせ返信</h1>

			<% if flash[:success] %>
				<div id="flash" class="alert alert-success" role="alert">
					<%= flash[:success] %>
				</div>
			<% end %>
			<% if flash[:error] %>
				<div id="flash" class="alert alert-danger" role="alert">
					<%= flash[:error] %>
				</div>
			<% end %>

			<%= form_for(@contact, url: admins_contact_path, method: :patch) do |f| %>
				<div class="field">
					<%= f.label :reply_language, "言語選択" %><br>
					<%= f.select :reply_language, [["日本語", 1],["英語", 2]] %>
				</div>
				<div class="field">
					<%= f.label :reply, "返信内容入力" %><br>
					<%= f.text_area :reply, autofocus: true, placeholder: "返信内容", :style=>"width: 100%; height: 200px;" %>
				</div>
				<div class="actions">
					<%= f.submit "送信" %>
				</div>
			<% end %>
			<table class="table table-bordered">
				<tr>
					<td style="width:150px;">返信内容</td>
					<td><%= @contact.reply %></td>
				</tr>
			</table>
		</div>
		<div class="col-md-6">
			<h4 style="text-decoration: underline;">英語のテンプレート</h4>
			<h4>Dear Mr./Ms.<%= @contact.user.name_last %>,</h4>
			<p>Thank you for your inquiry.<br>
			The following are answers to your inquiry.</p>

			<p style="color: red;">"こちらに返信内容が入ります。"</p>

			<p>Thank you for your continued support.</p>
			<p>Please do not reply to this email as this is a send-only address.</p>
			<h4 style="text-decoration: underline;">日本語のテンプレート</h4>
			<h4><%= @contact.user.name_last %> <%= @contact.user.name_first %> 様</h4>
			<p>この度は、お問い合わせありがとうございました。<br>
			お問い合わせの件下記にご回答申し上げます。</p>

			<p style="color: red;">"こちらに返信内容が入ります。"</p>

			<p>今後とも「Tricket Japan」をよろしくお願いいたします。</p>
			<p>尚、このメールにはご返信いただけません。</p>
		</div>
	</div>
</div>