config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  devise_for :users, :controllers => {
   :registrations => 'users/registrations',
  }

  root to: 'users#top'
  #users controller
  get '/users/:id/unsubscribe', to: 'users#unsubscribe', as: "users_unsubscribe"
  get '/users/unsubscribe/complete', to: 'users#complete'
  get '/users/:id/favorite', to: 'users#favorite', as: "user_favorite_page"
  patch '/users/:id/status_user', to: 'users#status_user', as: "user_status"
  get '/users/travelers', to: 'users#index_traveler'
  get '/users/travelers/search', to: 'users#search_traveler'
  get '/users/locals', to: 'users#index_local'
  get '/users/locals/search', to: 'users#search_local'
  get '/users/locals/sort', to: 'users#sort_local'
  resources :users, only: [:show, :edit, :update, :destroy]
  #posts controller
  get '/posts/top', to: 'posts#top'
  get '/posts/sort', to: 'posts#sort'
  get '/posts/photos', to: 'posts#index_photo', as: "photos"
  resources :posts do
    resources :likes, only:[:create, :destroy]
    resources :comments, only: [:create]
  end
  patch '/posts/:id/status_display', to: 'posts#status_display'
  patch '/posts/:id/status_accomplish', to: 'posts#status_accomplish', as: "status_accomplish"
  patch '/posts/:id/update_accomplish', to: 'posts#update_accomplish', as: "update_accomplish"
  patch '/posts/:id/reset_accomplish', to: 'posts#reset_accomplish', as: "reset_accomplish"
  #comments controller + 一部posts controller下へ
  resources :comments, only: [:edit, :update, :destroy]
  #likes controller  →  posts controller下へ
  #favorites controller
  resources :favorites, only: [:create, :destroy]
  #room controller
  patch '/rooms/status_open'
  resources :rooms, :only => [:create, :show, :index]
  #message controller
  resources :messages, :only => [:create]
  #contact controller
  resources :contacts, only: [:new, :create]
  #notification controller
  resources :notifications, only: [:index]

  #adminsファイル内のcontroller
  namespace :admins do
	  #admins/users controller
    get '/users/travelers', to: 'users#index_traveler'
    get '/users/travelers/search', to: 'users#search_traveler'
    get '/users/travelers/sort', to: 'users#sort_traveler'
    get '/users/locals', to: 'users#index_local'
    get '/users/locals/search', to: 'users#search_local'
    get '/users/locals/sort', to: 'users#sort_local'
    patch '/users/:id/restore', to: 'users#restore', as: "user_restore"
	  resources :users, only: [:show, :edit, :update, :destroy]
    #admins/posts controller
    get '/posts/search', to: 'posts#search'
    get '/posts/sort', to: 'posts#sort'
    patch '/posts/:id/restore', to: 'posts#restore', as: "post_restore"
    resources :posts, only:[:index, :show, :destroy]
    delete '/comments/:id', to: 'posts#comment_destroy', as: "comment_delete"
    #admins/contacts controller
    get '/contacts/search', to: 'contacts#search'
    resources :contacts, only:[:index, :show, :update]
  end
end

app/models/post.rb
class Post < ApplicationRecord

  acts_as_paranoid

	validates :title, presence: true, length: {in: 1..50}, uniqueness: { scope: :user_id }
	validates :content, presence: true, length: {in: 1..500}
	validates :time_todo, presence: true, length: {in: 1..50}
	validates :place_todo, presence: true, length: {in: 1..50}
  validates :area, presence: true
  validates :season, presence: true
  validates :interest, presence: true
  validates :status_accomplishment, presence: true
  validates :status_display, presence: true

	belongs_to :user
	has_many :likes, dependent: :destroy
	has_many :comments, dependent: :destroy
	has_many :notifications, dependent: :destroy

 	mount_uploader :post_image, ImageUploader
	mount_uploader :image_accomplishment, ImageUploader

	enum status_accomplishment: { Ongoing: 0, Accomplished: 1 }
  enum status_display: { open: 0, closed: 1 }

  scope :open, -> { where(status_display: 0) }

  def self.only_post_deleted_not_user
      self.with_deleted.where("name_user LIKE ?", "%%").joins(:user)
  end

  def liked_by?(user)
      likes.where(user_id: user.id).exists?
  end

  def create_notification_comment!(current_user, comment_id)
      other_user_ids = Comment.where(post_id: id).where.not(user_id: current_user.id).distinct.pluck(:user_id)
      other_user_ids.each do |other_user_id|
        save_notification_comment!(current_user, comment_id, other_user_id)
      end
      unless other_user_ids.include?(user_id)
        save_notification_comment!(current_user, comment_id, user_id)
      end
  end

  def save_notification_comment!(current_user, comment_id, visited_id)
      notification = current_user.active_notifications.new(
        post_id: id,
        comment_id: comment_id,
        visited_id: visited_id,
      )
      if notification.visitor_id == notification.visited_id
        notification.checked = true
      end
      if notification.valid?
        notification.save
      end
  end

  def create_notification_accomplish!(current_user)
      #Tricket達成通知
      other_user_ids = comments.where(post_id: id).where.not(user_id: current_user.id).distinct.pluck(:user_id)
      other_user_ids.each do |other_user_id|
        save_notification_accomplish!(current_user, other_user_id)
      end
  end

  def save_notification_accomplish!(current_user, visited_id)
      notification = current_user.active_notifications.new(
        post_id: id,
        visited_id: visited_id,
        accomplish: true
      )
      if notification.visitor_id == notification.visited_id
        notification.checked = true
      end
      if notification.valid?
        notification.save
      end
  end
end

app/controllers/admins/posts_controller.rb
class Admins::PostsController < ApplicationController

	before_action :authenticate_admin!

	def index
			@posts = Post.only_post_deleted_not_user.reverse #paranoia用
	end
	def search
			if params[:search_flag] == "1"
				@posts = Post.where("created_at LIKE ?", "%#{params[:date_search]}%")
			elsif params[:search_flag] == "2"
				@posts = Post.where("title LIKE ?", "%#{params[:title_search]}%")
			elsif params[:search_flag] == "3"
				if params[:delete_flag] == "0"
					@posts = Post.with_deleted.joins(:user).where("name_user LIKE ?", "%#{params[:user_search]}%")
				elsif params[:delete_flag] == "1"
					@posts = Post.joins(:user).where("name_user LIKE ?", "%#{params[:user_search]}%")
				elsif params[:delete_flag] == "2"
					@posts = Post.only_deleted.joins(:user).where("name_user LIKE ?", "%#{params[:user_search]}%")
				end
			end
			render :index
	end
	def sort
			if params[:sort_flag] == "1"
				@posts = Post.find(Like.group(:post_id).order('count(post_id) desc').pluck(:post_id))
				render :index
			else params[:sort_flag] == "2"
				@posts = Post.find(Like.group(:post_id).order('count(post_id) asc').pluck(:post_id))
				render :index
			end
	end
	def show
			@post = Post.with_deleted.find(params[:id])
			@user = @post.user
	end
	def destroy
      post = Post.find(params[:id])
      post.destroy
	end
	def restore
      post = Post.only_deleted.find(params[:id])
      post.restore
	end
	def comment_destroy
		  comment = Comment.find(params[:id])
      @post = Post.with_deleted.joins(:comments).where("comments.id = ?", comment.id).first
      comment.destroy
      redirect_to admins_user_path(comment.user)
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

	before_action :authenticate_user!, except: [:show]

	def top
		  @area = AREA
		  @season = SEASON
		  @interest = INTEREST
      @nationality = NATIOALITY
      @language = LANGUAGE
		  @users = User.where(type_user: 0)
		  @posts = Post.open.all
      @most_liked_posts = Post.find(Like.most_liked_postId)
		  @most_liked_posts_two = []
		  @most_liked_posts.each do |p|
        unless Post.find_by(id: p).nil? #gem"paranoia"用
    			post = Post.find(p.id)
    			if post.status_display_before_type_cast == 0
    				@most_liked_posts_two << post
    				if @most_liked_posts_two.count == 2 #ranking2位まで
    					break
    				end
    			end
        end
  		end
	end
	def index
  		@area = AREA
  		@season = SEASON
  		@interest = INTEREST
  		@posts = Post.open.all
	end
	def sort
  		@area = AREA
  		@season = SEASON
  		@interest = INTEREST
  		if params[:search_flag] == "1"
  			@posts = Post.open.where(area: params[:area])
  		elsif params[:search_flag] == "2"
  			@posts = Post.open.where(season: params[:season])
  		elsif  params[:search_flag] == "3"
  			@posts = Post.open.where(interest: params[:interest])
  		elsif  params[:search_flag] == "4"
  			@posts = Post.open.where(status_accomplishment: params[:status])
  		end
  		render :index
	end
	def show
      @post = Post.find(params[:id])
      @user = @post.user
      @count = @post.likes.count
      @favorite_count = @user.followers.count
		  @comment = Comment.new
      if current_user
      # 下記messageのroom
  	    @currentroomuser=RoomUser.where(user_id: current_user.id)
      	@roomuser=RoomUser.where(user_id: @user.id)
      	if @user.id != current_user.id
    			@currentroomuser.each do |cu|
      			@roomuser.each do |u|
      				if cu.room_id == u.room_id
      					@isRoom = true
      					@roomId = cu.room_id
      				end
            end
          end
  		    if @isRoom
  		    else
  		      @room = Room.new
  		      @roomusernew = RoomUser.new
  		    end
  	    end
		  end
	end
	def update_accomplish
      @post = Post.find(params[:id])
      if @post.update(post_params)
        flash[:accomplish] = "You have posted accomplishment successfully."
        @post.update(status_accomplishment: 1)
        @post.create_notification_accomplish!(current_user)
        redirect_to post_path(@post.id)
      else
        flash[:error] = "error!!"
        redirect_to post_path(@post.id)
      end
	end
	def reset_accomplish
      @post = Post.find(params[:id])
      if @post.update(status_accomplishment: 0, image_accomplishment: nil, comment_accomplishment: nil, address: nil)
        flash[:accomplish] = "You have reset accomplishment successfully."
        redirect_to post_path(@post.id)
      else
        flash[:error] = "error!!"
        redirect_to post_path(@post.id)
      end
	end
	def new
  		@area = AREA
  		@season = SEASON
  		@interest = INTEREST
  		@post = Post.new
	end
	def create
  		@post = Post.new(post_params)
  		@area = AREA
  		@season = SEASON
  		@interest = INTEREST
    	@post.user_id = current_user.id
    	if  @post.save
    		flash[:success] = "You have posted the Tricket successfully."
    		redirect_to post_path(@post)
      else
      	flash[:error] = "error!!"
      	render :new
      end
	end
	def edit
  		@area = AREA
  		@season = SEASON
  		@interest = INTEREST
      @post = Post.find(params[:id])
		  if @post.user != current_user
        redirect_to posts_top_path
      else
      	@post = Post.find(params[:id])
      	render :edit
      end
	end
	def update
      @post = Post.find(params[:id])
  		@area = AREA
  		@season = SEASON
  		@interest = INTEREST
      if @post.update(post_params)
        flash[:success] = "You have edited the Tricket successfully."
        redirect_to post_path(@post.id)
      else
        flash[:error] = "error!!"
        render :edit
      end
	end
	def destroy
      post = Post.find(params[:id])
      post.destroy
      redirect_to user_path(current_user)
	end
  def index_photo
      @posts = Post.open.all
  end

	private
    def post_params
      params.require(:post).permit(:title, :content, :area, :season, :interest, :time_todo, :place_todo, :status_display, :post_image, :image_accomplishment, :comment_accomplishment, :address)
    end
end

app/helpers/admins/posts_helper.rb
module Admins::PostsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/edit.html.erb
<div class="container-fluid">
	<div class="row" style="background-color: #EFE9D1;">
		<div class="col-md-6">
			<h1 class="title_type1_traveler">Edit Tricket</h1>

			<% if flash[:error] %>
				<div id="flash" class="alert alert-danger" role="alert">
					<%= flash[:error] %>
				</div>
			<% end %>
			<% if @post.errors.any? %>
			  <div class="alert alert-warning">
			    <ul>
			      <% @post.errors.full_messages.each do |message| %>
			        <li><%= message %></li>
			      <% end %>
			    </ul>
			  </div>
			<% end %>

			<%= form_for(@post) do |f| %>
	    <div class="field">
	      <%= f.label :title %>
	      <%= f.text_field :title, autofocus: true, placeholder: "title", :style=>"width: 400px;" %>
	    </div>
	    <div class="field">
    		<%= f.label :post_image %>
    		<%= f.file_field :post_image, accept: 'image/jpeg,image/gif,image/png,video/*' %>
  		</div>
	    <div class="field">
	      <%= f.label :display_choice %>
	      <%= f.select :status_display, [["open", "open"],["closed", "closed"]] %>
	    </div>
	    <div class="field">
	      <%= f.label :area %>
    		<%= f.select :area, @area %>
	      <%= f.label :season %>
    		<%= f.select :season, @season %>
	      <%= f.label :interest %>
    		<%= f.select :interest, @interest %>
	    </div>
	    <div class="field">
	      <%= f.label :when %>
	      <%= f.text_field :time_todo, autofocus: true, placeholder: "when do you wanna accomplish?", :style=>"width: 300px;" %>
	    </div>
	    <div class="field">
	      <%= f.label :where %>
	      <%= f.text_field :place_todo, autofocus: true, placeholder: "where do you wanna accomplish?", :style=>"width: 300px;" %>
	    </div>
	    <div class="field">
	      <%= f.label :content %><br>
	      <%= f.text_area :content, autofocus: true, placeholder: "content", :style=>"width: 450px; height: 200px;" %>
	    </div>
		</div>
	</div>
	<div class="row" style="background-color: #EFE9D1;">
	  <div class="col-md-12">
	    <div class="actions" style="width: 100%; margin: 0 auto;">
	      <%= f.submit "update", :style=>"background-color: #c77eb5; color: white; width: 100px; border-radius: 5px;" %>
	      <%= link_to "delete Tricket", post_path(@post), method: :delete, data: { confirm: "Are you sure to delete this Tricket?" }, class:"label label-default", :style=>"background-color: red;" %>
	    </div>
	    <% end %>
	    <h4><%= link_to "mypage", user_path(current_user), class:"label label-default", :style=>"background-color: #c77eb5;" %></h4>
	  </div>
	</div>
</div>

app/views/posts/index.html.erb
<div class="container-fluid">
	<div class="row">
		<div class="Trickets-index-background1">
			<div class="col-md-12">
			<h1 class="title_type1_traveler">Trickets</h1>
			</div>
		</div>
	</div>
	<div class="row">
		<div class="col-md-12">
			<div class="Trickets-index-headline clearfix">
				<div class="search-form-tag">
					<%= form_tag(posts_sort_path, method: :get) do %>
						<%= label_tag "area" %>
						<%= hidden_field_tag :search_flag, 1 %>
						<%= select_tag "area", options_for_select(@area) %>
						<%= submit_tag "search", :style=>"background-color: #c77eb5; color: white; width: 50px; border-radius: 5px;" %>
					<% end %>
				</div>
				<div class="search-form-tag">
					<%= form_tag(posts_sort_path, method: :get) do %>
						<%= label_tag "season" %>
						<%= hidden_field_tag :search_flag, 2 %>
						<%= select_tag "season", options_for_select(@season) %>
						<%= submit_tag "search", :style=>"background-color: #c77eb5; color: white; width: 50px; border-radius: 5px;" %>
					<% end %>
				</div>
				<div class="search-form-tag">
					<%= form_tag(posts_sort_path, method: :get) do %>
						<%= label_tag "interest" %>
						<%= hidden_field_tag :search_flag, 3 %>
						<%= select_tag "interest", options_for_select(@interest) %>
						<%= submit_tag "search", :style=>"background-color: #c77eb5; color: white; width: 50px; border-radius: 5px;" %>
					<% end %>
				</div>
				<div class="search-form-tag">
					<%= form_tag(posts_sort_path, method: :get) do %>
						<%= label_tag "status" %>
						<%= hidden_field_tag :search_flag, 4 %>
						<%= select_tag "status", options_for_select({ongoing: 0, accomplished: 1}) %>
						<%= submit_tag "search", :style=>"background-color: #c77eb5; color: white; width: 50px; border-radius: 5px;" %>
					<% end %>
				</div>
			</div>
			<% if @posts.present? %>
			<% @posts.reverse.each do |p| %>
				<div class="Trickets-index-content">
					<div style="width: 15%; float:left;">
						<div class="Trickets-top-user-image">
							<% if p.user.picture_profile? %>
								<%= image_tag asset_path p.user.picture_profile.profile.url %>
							<% else %>
								<%= image_tag asset_path "default.jpg" %>
							<% end %>
							<p style="text-align:center;"><%= p.user.nationality %></p>
						</div>
					</div>
					<div class="panel panel-default" style="width: 80%; float:left;">
						<div class="panel-heading" style="background-color:#f8b500;">
							<h5 class="panel-title">Title: <%= p.title.truncate(40) %></h5>
						</div>
						<div class="panel-body">
							<h4 class="label label-default"><%= p.area %></h4>
							<h4 class="label label-default"><%= p.season %></h4>
							<h4 class="label label-default"><%= p.interest %></h4>
							<% if p.status_accomplishment_before_type_cast == 1 %>
								<h4 class="label label-success"><%= p.status_accomplishment %></h4>
							<% end %>
							<div style="float:right;">
								<%= link_to "Tricket detail", post_path(p.id), class:"label label-default", :style=>"background-color: #c77eb5" %>
								<% if @user == current_user %>
									<%= link_to "edit Tricket", edit_post_path(p.id), class:"label label-default", :style=>"background-color: #c77eb5" %>
								<% end %>
							</div>
						</div>
					</div>
				</div>
			<% end %>
		</div>
		<% else %>
			<h1>Not applicable.</h1>
		<% end %>
	</div>
	<h4 style="text-align: center;"><%= link_to "back", posts_top_path, class:"label label-default", :style=>"background-color: #c77eb5" %></h4>
</div>

app/views/posts/index_photo.html.erb
<div class="container-fluid">
  <div class="row" style="background-color:#EFE9D1;">
    <div class="col-md-12">
      <h1 class="title_type1_traveler">Accomplishment Photos</h1>
      <div class="photo-content clearfix">
        <% @posts.reverse.each do |p| %>
          <% if p.status_accomplishment_before_type_cast == 1 %>
            <% if p.image_accomplishment? %>
              <% if p.image_accomplishment.file.content_type.include?('image/') %>
                <div class="photo-items">
                  <div class="photo-img">
                    <%= link_to post_path(p.id) do %>
                      <%= image_tag asset_path p.image_accomplishment.post.url %>
                    <% end %>
                  </div>
                  <div class="photo-text">
                    <% if p.user.picture_profile? %>
                      <%= image_tag asset_path p.user.picture_profile.profile.url %>
                    <% end %>
                    <%= p.user.name_user %>
                  </div>
                </div>
              <% elsif p.image_accomplishment.file.content_type.include?('video/') %>
                <div class="video-items">
                  <div class="video-img">
                    <%= link_to post_path(p.id) do %>
                      <%= video_tag p.image_accomplishment.url, width: "330px", height: "230px",autobuffer: true, autoplay: true, muted: true, loop: :true %>
                    <% end %>
                  </div>
                  <div class="video-text">
                    <% if p.user.picture_profile? %>
                      <%= image_tag asset_path p.user.picture_profile.profile.url %>
                    <% end %>
                    <%= p.user.name_user %>
                  </div>
                </div>
              <% end %>
            <% end %>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/posts/top.html.erb
<div class="container-fluid">
	<div class="row">
		<div class="Trickets-top-background1">
			<div class="col-md-12">
				<h1 class="title_type1_traveler">Trickets&Travelers</h1>
			</div>
		</div>
	</div>
	<div class="row" style="height:330px; background-color:#EFE9D1;">
		<div class="col-md-12">
			<h1 class="title_type1_traveler">Most liked Trickets (monthly)</h1>
			<% @most_liked_posts_two.each do |p| %>
				<h2 class="ranking-number"><%= p.likes.where(created_at: 1.month.ago.beginning_of_day..Time.zone.now.end_of_day).count %> likes</h2>
				<div class="Trickets-top-content clearfix">
					<div style="width: 15%; float:left;">
						<div class="Trickets-top-user-image">
							<% if p.user.picture_profile? %>
								<%= image_tag asset_path p.user.picture_profile.profile.url %>
							<% else %>
								<%= image_tag asset_path "default.jpg" %>
							<% end %>
							<p style="text-align:center;"><%= p.user.nationality %></p>
						</div>
					</div>
					<div class="panel panel-default" style="width: 80%; float:left;">
						<div class="panel-heading" style="background-color:#f8b500;">
							<h5 class="panel-title">Title: <%= p.title.truncate(40) %></h5>
						</div>
						<div class="panel-body">
							<h4 class="label label-default"><%= p.area %></h4>
							<h4 class="label label-default"><%= p.season %></h4>
							<h4 class="label label-default"><%= p.interest %></h4>
							<% if p.status_accomplishment_before_type_cast == 1 %>
								<h4 class="label label-success"><%= p.status_accomplishment %></h4>
							<% end %>
							<div style="float:right;">
								<%= link_to "Tricket detail", post_path(p.id), class:"label label-default", :style=>"background-color: #c77eb5" %>
								<% if @user == current_user %>
								<%= link_to "edit Tricket", edit_post_path(p.id), class:"label label-default", :style=>"background-color: #c77eb5" %>
								<% end %>
							</div>
						</div>
					</div>
				</div>
			<% end %>
		</div>
	</div>
	<div class="row">
		<div class="col-md-12">
			<div class="Trickets-top-headline clearfix">
				<h1 class="title_type1_traveler">Trickets</h1>
				<div class="search-form-tag">
					<%= form_tag(posts_sort_path, method: :get) do %>
						<%= label_tag "area" %>
						<%= hidden_field_tag :search_flag, 1 %>
						<%= select_tag "area", options_for_select(@area) %>
						<%= submit_tag "search", :style=>"background-color: #c77eb5; color: white; width: 50px; border-radius: 5px;" %>
					<% end %>
				</div>
				<div class="search-form-tag">
					<%= form_tag(posts_sort_path, method: :get) do %>
						<%= label_tag "season" %>
						<%= hidden_field_tag :search_flag, 2 %>
						<%= select_tag "season", options_for_select(@season) %>
						<%= submit_tag "search", :style=>"background-color: #c77eb5; color: white; width: 50px; border-radius: 5px;" %>
					<% end %>
				</div>
				<div class="search-form-tag">
					<%= form_tag(posts_sort_path, method: :get) do %>
						<%= label_tag "interest" %>
						<%= hidden_field_tag :search_flag, 3 %>
						<%= select_tag "interest", options_for_select(@interest) %>
						<%= submit_tag "search", :style=>"background-color: #c77eb5; color: white; width: 50px; border-radius: 5px;" %>
					<% end %>
				</div>
				<div class="search-form-tag">
					<%= form_tag(posts_sort_path, method: :get) do %>
						<%= label_tag "status" %>
						<%= hidden_field_tag :search_flag, 4 %>
						<%= select_tag "status", options_for_select({ongoing: 0, accomplished: 1}) %>
						<%= submit_tag "search", :style=>"background-color: #c77eb5; color: white; width: 50px; border-radius: 5px;" %>
					<% end %>
				</div>
			</div>
			<% @posts.reverse.first(4).each do |p| %>
			<div class="Trickets-top-content clearfix">
				<div style="width: 15%; float:left;">
					<div class="Trickets-top-user-image clearfix">
						<% if p.user.picture_profile? %>
							<%= image_tag asset_path p.user.picture_profile.profile.url %>
						<% else %>
							<%= image_tag asset_path "default.jpg" %>
						<% end %>
						<p style="text-align:center;"><%= p.user.nationality %></p>
					</div>
				</div>
				<div class="panel panel-default" style="width: 80%; float:left;">
					<div class="panel-heading" style="background-color:#f8b500;">
						<h5 class="panel-title">Title: <%= p.title.truncate(40) %></h5>
					</div>
					<div class="panel-body">
						<h4 class="label label-default"><%= p.area %></h4>
						<h4 class="label label-default"><%= p.season %></h4>
						<h4 class="label label-default"><%= p.interest %></h4>
						<% if p.status_accomplishment_before_type_cast == 1 %>
							<h4 class="label label-success"><%= p.status_accomplishment %></h4>
						<% end %>
						<div style="float:right;">
							<%= link_to "Tricket detail", post_path(p.id), class:"label label-default", :style=>"background-color: #c77eb5" %>
						</div>
					</div>
				</div>
			</div>
			<% end %>
		</div>
		<h4 style="text-align: center;"><%= link_to "check more Trickets", posts_path, class:"label label-default", :style=>"background-color: #c77eb5; margin-top: 30px;"%></h4>
	</div>
	<div class="row" style="background-color:#EFE9D1;">
		<div class="col-md-12">
			<div class="travelers-top-headline clearfix">
				<h1 class="title_type1_traveler">Travelers</h1>
				<div class="search-form-tag">
					<%= form_tag(users_travelers_search_path, method: :get) do %>
						<%= label_tag "traveler_name" %>
						<%= hidden_field_tag :search_flag, 1 %>
						<%= text_field_tag :user_search %>
						<%= submit_tag "search", :style=>"background-color: #c77eb5; color: white; width: 50px; border-radius: 5px;"  %>
					<% end %>
				</div>
				<div class="search-form-tag">
					<%= form_tag(users_travelers_search_path, method: :get) do %>
						<%= label_tag "nationality" %>
						<%= hidden_field_tag :search_flag, 2 %>
						<%= select_tag "nationality", options_for_select(@nationality) %>
						<%= submit_tag "search", :style=>"background-color: #c77eb5; color: white; width: 50px; border-radius: 5px;"  %>
					<% end %>
				</div>
				<div class="search-form-tag">
					<%= form_tag(users_travelers_search_path, method: :get) do %>
						<%= label_tag "language" %>
						<%= hidden_field_tag :search_flag, 3 %>
						<%= select_tag "language", options_for_select(@language) %>
						<%= submit_tag "search", :style=>"background-color: #c77eb5; color: white; width: 50px; border-radius: 5px;"  %>
					<% end %>
				</div>
			</div>
			<div class="travelers-top-content clearfix">
				<% @users.reverse.first(5).each do |user| %>
				<div class="travelers-index-items">
					<%= link_to user_path(user) do %>
						<div class="thumbnail">
							<% if user.picture_profile? %>
								<%= image_tag asset_path user.picture_profile.profile.url %>
							<% else %>
								<%= image_tag asset_path "default.jpg" %>
							<% end %>
							<div class="caption">
								<h4><%= user.name_user %></h4>
								<p>Nationality: <%= user.nationality %></p>
								<p>Age: <%= (Date.today.strftime("%Y%m%d").to_i - user.birthday.strftime("%Y%m%d").to_i) / 10000 %></p>
							</div>
						</div>
					<% end %>
				</div>
				<% end %>
			</div>
			<h4 style="text-align: center;"><%= link_to "check more Travelers", users_travelers_path, class:"label label-default", :style=>"background-color: #c77eb5; margin-top: 30px;"%></h4>
		</div>
	</div>
</div>